# Generated by Django 5.2.6 on 2026-08-31 04:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicalHistory',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
                ('clinical_history_id', models.BigAutoField(db_column='clinical_history_id', primary_key=True, serialize=False)),
                ('last_ai_summary', models.TextField(blank=True, db_column='last_ai_summary', null=True)),
                ('last_ai_summary_at', models.DateTimeField(blank=True, db_column='last_ai_summary_at', null=True)),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, db_column='updated_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'clinical_history',
            },
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
                ('note_id', models.BigAutoField(db_column='note_id', primary_key=True, serialize=False)),
                ('text', models.TextField(db_column='text')),
                ('clinical_history', models.ForeignKey(db_column='clinical_history_id', on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='people.clinicalhistory')),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, db_column='updated_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'note',
            },
        ),
        migrations.CreateModel(
            name='Pathology',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
                ('pathology_id', models.BigAutoField(db_column='pathology_id', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='name', max_length=255, unique=True)),
                ('description', models.TextField(blank=True, db_column='description', null=True)),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, db_column='updated_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'pathology',
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
                ('patient_id', models.BigAutoField(db_column='patient_id', primary_key=True, serialize=False)),
                ('identification_number', models.TextField(blank=True, db_column='identification_number', null=True, unique=True)),
                ('first_name', models.CharField(db_column='first_name', max_length=100)),
                ('last_name', models.CharField(db_column='last_name', max_length=100)),
                ('date_of_birth', models.DateField(blank=True, db_column='date_of_birth', null=True)),
                ('phone', models.CharField(blank=True, db_column='phone', max_length=30, null=True)),
                ('email', models.EmailField(blank=True, db_column='email', max_length=255, null=True)),
                ('address', models.CharField(blank=True, db_column='address', max_length=255, null=True)),
                ('is_active', models.BooleanField(db_column='is_active', default=True)),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, db_column='updated_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'patient',
            },
        ),
        migrations.AddField(
            model_name='clinicalhistory',
            name='patient',
            field=models.OneToOneField(db_column='patient_id', on_delete=django.db.models.deletion.PROTECT, related_name='clinical_history', to='people.patient'),
        ),
        migrations.CreateModel(
            name='PatientPathology',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
                ('patient_pathology_id', models.BigAutoField(db_column='patient_pathology_id', primary_key=True, serialize=False)),
                ('is_primary', models.BooleanField(blank=True, db_column='is_primary', null=True)),
                ('diagnosis_date', models.DateField(blank=True, db_column='diagnosis_date', null=True)),
                ('notes', models.TextField(blank=True, db_column='notes', null=True)),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('pathology', models.ForeignKey(db_column='pathology_id', on_delete=django.db.models.deletion.PROTECT, related_name='patient_links', to='people.pathology')),
                ('patient', models.ForeignKey(db_column='patient_id', on_delete=django.db.models.deletion.PROTECT, related_name='pathologies', to='people.patient')),
                ('updated_by', models.ForeignKey(blank=True, db_column='updated_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'patient_pathology',
            },
        ),
        migrations.CreateModel(
            name='ClinicalHistoryEntry',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
                ('clinical_history_entry_id', models.BigAutoField(db_column='clinical_history_entry_id', primary_key=True, serialize=False)),
                ('entry_type', models.CharField(blank=True, choices=[('DIAGNOSIS', 'Diagnostico'), ('TREATMENT', 'Tratamiento'), ('OBSERVATION', 'Observacion'), ('PROCEDURE', 'Procedimiento'), ('FOLLOW_UP', 'Seguimiento')], db_column='entry_type', max_length=30, null=True)),
                ('entry_date', models.DateField(db_column='entry_date')),
                ('description', models.TextField(db_column='description')),
                ('clinical_history', models.ForeignKey(db_column='clinical_history_id', on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='people.clinicalhistory')),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, db_column='updated_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'clinical_history_entry',
                'constraints': [models.CheckConstraint(condition=models.Q(('entry_type__in', ['DIAGNOSIS', 'TREATMENT', 'OBSERVATION', 'PROCEDURE', 'FOLLOW_UP']), ('entry_type__isnull', True), _connector='OR'), name='ck_clinical_history_entry_type')],
            },
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['last_name', 'first_name'], name='ix_patient_name'),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['is_active'], name='ix_patient_is_active'),
        ),
        migrations.AddConstraint(
            model_name='patientpathology',
            constraint=models.UniqueConstraint(fields=('patient', 'pathology'), name='uq_patient_pathology'),
        ),
        migrations.AddConstraint(
            model_name='patientpathology',
            constraint=models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('patient',), name='uq_patient_primary_pathology'),
        ),
    ]
