# Generated by Django 5.2.6 on 2026-08-31 04:33

import apps.core.managers
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('user_id', models.BigAutoField(db_column='user_id', primary_key=True, serialize=False)),
                ('username', models.TextField(blank=True, db_column='username', null=True, unique=True)),
                ('email', models.TextField(blank=True, db_column='email', null=True, unique=True, validators=[django.core.validators.EmailValidator()])),
                ('is_active', models.BooleanField(db_column='is_active', default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'db_table': 'user',
            },
            managers=[
                ('objects', apps.core.managers.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('audit_id', models.BigAutoField(db_column='audit_id', primary_key=True, serialize=False)),
                ('entity_type', models.CharField(db_column='entity_type', max_length=100)),
                ('entity_id', models.BigIntegerField(db_column='entity_id')),
                ('action', models.CharField(blank=True, choices=[('CREATE', 'Creacion'), ('UPDATE', 'Actualizacion'), ('DELETE', 'Eliminacion')], db_column='action', max_length=30, null=True)),
                ('old_values', models.JSONField(blank=True, db_column='old_values', null=True)),
                ('new_values', models.JSONField(blank=True, db_column='new_values', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.PROTECT, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'audit_log',
                'indexes': [models.Index(fields=['entity_type', 'entity_id'], name='ix_audit_log_entity'), models.Index(fields=['created_at'], name='ix_audit_log_created_at')],
                'constraints': [models.CheckConstraint(condition=models.Q(('action__in', ['CREATE', 'UPDATE', 'DELETE']), ('action__isnull', True), _connector='OR'), name='ck_audit_log_action')],
            },
        ),
    ]
