# Generated by Django 5.2.6 on 2026-08-31 04:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportBatch',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
                ('import_batch_id', models.BigAutoField(db_column='import_batch_id', primary_key=True, serialize=False)),
                ('source_file_name', models.CharField(db_column='source_file_name', max_length=255)),
                ('source_file_type', models.CharField(blank=True, db_column='source_file_type', max_length=50, null=True)),
                ('processed_at', models.DateTimeField(blank=True, db_column='processed_at', null=True)),
                ('total_rows', models.IntegerField(blank=True, db_column='total_rows', null=True)),
                ('success_count', models.IntegerField(blank=True, db_column='success_count', null=True)),
                ('failure_count', models.IntegerField(blank=True, db_column='failure_count', null=True)),
                ('status', models.CharField(blank=True, choices=[('PENDING', 'Pendiente'), ('PROCESSING', 'Procesando'), ('COMPLETED', 'Completado'), ('COMPLETED_WITH_ERRORS', 'Completado con errores'), ('FAILED', 'Fallido')], db_column='status', max_length=30, null=True)),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, db_column='updated_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'import_batch',
            },
        ),
        migrations.CreateModel(
            name='ImportBatchRow',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
                ('import_batch_row_id', models.BigAutoField(db_column='import_batch_row_id', primary_key=True, serialize=False)),
                ('row_number', models.IntegerField(db_column='row_number')),
                ('identification_number', models.CharField(blank=True, db_column='identification_number', max_length=50, null=True)),
                ('patient_name_snapshot', models.CharField(blank=True, db_column='patient_name_snapshot', max_length=255, null=True)),
                ('pathology_name_snapshot', models.CharField(blank=True, db_column='pathology_name_snapshot', max_length=255, null=True)),
                ('status', models.CharField(blank=True, choices=[('PENDING', 'Pendiente'), ('SUCCESS', 'Exito'), ('ERROR', 'Error')], db_column='status', max_length=30, null=True)),
                ('error_message', models.TextField(blank=True, db_column='error_message', null=True)),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('import_batch', models.ForeignKey(db_column='import_batch_id', on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='massive_load.importbatch')),
                ('updated_by', models.ForeignKey(blank=True, db_column='updated_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'import_batch_row',
            },
        ),
        migrations.AddConstraint(
            model_name='importbatch',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['PENDING', 'PROCESSING', 'COMPLETED', 'COMPLETED_WITH_ERRORS', 'FAILED']), ('status__isnull', True), _connector='OR'), name='ck_import_batch_status'),
        ),
        migrations.AddConstraint(
            model_name='importbatchrow',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['PENDING', 'SUCCESS', 'ERROR']), ('status__isnull', True), _connector='OR'), name='ck_import_batch_row_status'),
        ),
    ]
