# Generated by Django 5.2.6 on 2026-08-31 04:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('people', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TreatmentPlan',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
                ('treatment_plan_id', models.BigAutoField(db_column='treatment_plan_id', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='name', max_length=255)),
                ('start_date', models.DateField(db_column='start_date')),
                ('end_date', models.DateField(blank=True, db_column='end_date', null=True)),
                ('status', models.CharField(blank=True, choices=[('DRAFT', 'Borrador'), ('ACTIVE', 'Activo'), ('COMPLETED', 'Completado'), ('CANCELLED', 'Cancelado')], db_column='status', max_length=30, null=True)),
                ('clinical_note', models.TextField(blank=True, db_column='clinical_note', null=True)),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('pathology', models.ForeignKey(blank=True, db_column='pathology_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='treatment_plans', to='people.pathology')),
                ('patient', models.ForeignKey(db_column='patient_id', on_delete=django.db.models.deletion.PROTECT, related_name='treatment_plans', to='people.patient')),
                ('updated_by', models.ForeignKey(blank=True, db_column='updated_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'treatment_plan',
            },
        ),
        migrations.CreateModel(
            name='TreatmentPlanMedication',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
                ('treatment_plan_medication_id', models.BigAutoField(db_column='treatment_plan_medication_id', primary_key=True, serialize=False)),
                ('external_medication_id', models.CharField(db_column='external_medication_id', max_length=100)),
                ('medication_name_snapshot', models.TextField(blank=True, db_column='medication_name_snapshot', null=True)),
                ('medication_family_snapshot', models.TextField(blank=True, db_column='medication_family_snapshot', null=True)),
                ('dose', models.CharField(blank=True, db_column='dose', max_length=100, null=True)),
                ('frequency', models.CharField(blank=True, db_column='frequency', max_length=100, null=True)),
                ('duration', models.CharField(blank=True, db_column='duration', max_length=100, null=True)),
                ('route', models.CharField(blank=True, db_column='route', max_length=100, null=True)),
                ('instructions', models.TextField(blank=True, db_column='instructions', null=True)),
                ('validation_status', models.CharField(blank=True, db_column='validation_status', max_length=30, null=True)),
                ('warning_flag', models.BooleanField(blank=True, db_column='warning_flag', null=True)),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('treatment_plan', models.ForeignKey(db_column='treatment_plan_id', on_delete=django.db.models.deletion.CASCADE, related_name='medications', to='medications.treatmentplan')),
                ('updated_by', models.ForeignKey(blank=True, db_column='updated_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'treatment_plan_medication',
            },
        ),
        migrations.AddConstraint(
            model_name='treatmentplan',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['DRAFT', 'ACTIVE', 'COMPLETED', 'CANCELLED']), ('status__isnull', True), _connector='OR'), name='ck_treatment_plan_status'),
        ),
    ]
