# Generated by Django 5.2.6 on 2026-08-31 04:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('people', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
                ('appointment_id', models.BigAutoField(db_column='appointment_id', primary_key=True, serialize=False)),
                ('scheduled_at', models.DateTimeField(db_column='scheduled_at')),
                ('status', models.CharField(blank=True, choices=[('SCHEDULED', 'Agendada'), ('CONFIRMED', 'Confirmada'), ('COMPLETED', 'Atendida'), ('CANCELLED', 'Cancelada'), ('NO_SHOW', 'No asistio')], db_column='status', max_length=30, null=True)),
                ('reason', models.TextField(blank=True, db_column='reason', null=True)),
                ('priority', models.CharField(blank=True, choices=[('URGENT', 'Urgente'), ('ROUTINE_CONTROL', 'Control de Rutina'), ('POST_OPERATIVE', 'Post-operatorio')], db_column='priority', max_length=30, null=True)),
                ('priority_suggested_by_ai', models.CharField(blank=True, db_column='priority_suggested_by_ai', max_length=30, null=True)),
                ('priority_final', models.CharField(blank=True, db_column='priority_final', max_length=30, null=True)),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(db_column='patient_id', on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='people.patient')),
                ('updated_by', models.ForeignKey(blank=True, db_column='updated_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'appointment',
            },
        ),
        migrations.CreateModel(
            name='AppointmentReminder',
            fields=[
                ('reminder_id', models.BigAutoField(db_column='reminder_id', primary_key=True, serialize=False)),
                ('channel', models.CharField(blank=True, choices=[('EMAIL', 'Email'), ('SMS', 'SMS')], db_column='channel', max_length=30, null=True)),
                ('scheduled_at', models.DateTimeField(db_column='scheduled_at')),
                ('sent_at', models.DateTimeField(blank=True, db_column='sent_at', null=True)),
                ('status', models.CharField(blank=True, choices=[('PENDING', 'Pendiente'), ('SENT', 'Enviado'), ('FAILED', 'Fallido')], db_column='status', max_length=30, null=True)),
                ('failure_reason', models.TextField(blank=True, db_column='failure_reason', null=True)),
                ('appointment', models.ForeignKey(db_column='appointment_id', on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='appointments.appointment')),
            ],
            options={
                'db_table': 'appointment_reminder',
            },
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['scheduled_at'], name='ix_appointment_scheduled_at'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['patient', 'scheduled_at'], name='ix_appointment_patient_date'),
        ),
        migrations.AddConstraint(
            model_name='appointment',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['SCHEDULED', 'CONFIRMED', 'COMPLETED', 'CANCELLED', 'NO_SHOW']), ('status__isnull', True), _connector='OR'), name='ck_appointment_status'),
        ),
        migrations.AddConstraint(
            model_name='appointment',
            constraint=models.CheckConstraint(condition=models.Q(('priority__in', ['URGENT', 'ROUTINE_CONTROL', 'POST_OPERATIVE']), ('priority__isnull', True), _connector='OR'), name='ck_appointment_priority'),
        ),
        migrations.AddIndex(
            model_name='appointmentreminder',
            index=models.Index(fields=['status', 'scheduled_at'], name='ix_reminder_status_date'),
        ),
        migrations.AddConstraint(
            model_name='appointmentreminder',
            constraint=models.CheckConstraint(condition=models.Q(('channel__in', ['EMAIL', 'SMS']), ('channel__isnull', True), _connector='OR'), name='ck_appointment_reminder_channel'),
        ),
        migrations.AddConstraint(
            model_name='appointmentreminder',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['PENDING', 'SENT', 'FAILED']), ('status__isnull', True), _connector='OR'), name='ck_appointment_reminder_status'),
        ),
    ]
